apiVersion: v1
kind: Service
metadata:
  name: nodejs-exposed-service
spec:
  type: LoadBalancer  
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  
